name: Cypress Tests

on:
  push:
    branches: [ main ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Cypress
      uses: cypress-io/github-action@v6
      with:
        start: npm start
        wait-on: 'http://localhost:3000'
        record: true
        key: fed40982-547c-4cd4-b3c9-02a1ea91a286
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
